export const skills = [
  "Collaboration",
  "Communication",
  "Critical thinking",
  "Customer Service",
  "Decision-Making",
  "Delegation",
  "Innovation",
  "Interpersonal",
  "Leadership",
  "Management",
  "Motivation",
  "Observation",
  "Organization",
  "Planning",
  "Problem-solving",
  "Team-Building",
  "Teamwork",
  "Time-Management",
];
